name: lab_task2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
